feat: Add migration scripts to add initial workflows, tasks and handler
KeyValueSoftwareSystems/oss-conductor pull request #3
Opened 2024-02-20 04:23 UTC by muhammad-keyvalue

2024-02-20 08:31 UTC, raveenapv approved these changes, later dismissed

2024-02-20 08:32 UTC, Sherif-kv approved these changes, later dismissed

2024-03-01 09:49 UTC, muhammad-keyvalue commented on rest/src/main/resources/siren/workflows/sirenWebhookWorkflow.json
> +        "notificationAuditId": "${workflow.input.notificationAuditId}"
Add parameter for traceId with value ${workflow.input.traceId}

2024-03-04 04:49 UTC, sreeraj-keyvalue requested changes

2024-03-04 04:49 UTC, sreeraj-keyvalue commented on rest/src/main/resources/siren/eventhandlers/finalizeWorkflowExecutionEventHandler.json
> +        "name": "finalize_workflow_execution",
Incorrect workflow name

2024-03-06 08:39 UTC, Sherif-kv approved these changes

2024-03-06 08:40 UTC, sreeraj-keyvalue approved these changes

2024-03-06 08:41 UTC, merged